SELECT * FROM usedCar;
DELETE FROM usedCar WHERE site = 'KB';
SELECT * FROM KBModel;
SELECT count(*) FROM KBmodel;
SELECT * FROM KCarModel;
SELECT count(*) FROM KCarmodel;
SELECT * FROM BobaeModel;
SELECT DISTINCT manufacturer1 FROM BobaeModel WHERE manufacturer1 LIKE '%기타%';
SELECT count(*) FROM Bobaemodel;
SELECT * FROM EncarModel;
SELECT count(*) FROM Encarmodel;
SELECT count(*) as 'count', AVG(price) as 'priceAVG', AVG(distance) as 'distAVG' FROM usedCar;
SELECT * FROM carModel ORDER BY manufacturer;
SELECT * FROM carModel;
SELECT DISTINCT model FROM carModel;
SELECT DISTINCT model FROM carModel WHERE model != '기타';
SELECT COUNT(*) FROM carModel;
SELECT * FROM carModel WHERE model = 'K9' ORDER BY manufacturer;
SELECT * FROM testCar;
SELECT * FROM usedCar WHERE model_detail = '더 뉴 렉스턴 스포츠';
SELECT * FROM testtoken;
SELECT * FROM userTable;
SELECT count(*) as count FROM userTable WHERE userid = 'test1234';
#drop table userTable;
SELECT DISTINCT model FROM carModel WHERE manufacturer = '기아';
SELECT DISTINCT manufacturer FROM carModel;
SELECT DISTINCT manufacturer FROM carModel WHERE manufacturer Like '%현대%';
SELECT DISTINCT model, model_detail FROM carModel WHERE manufacturer = '제네시스' ORDER BY model;
SELECT * FROM carModel WHERE manufacturer = '현대' and model = '쏘나타' ORDER BY model_detail;
SELECT * FROM carModel WHERE model_detail Like '%쏘나타%';
SELECT * FROM testToken;
SELECT * FROM Notification;
INSERT INTO Notification VALUES(NULL, "kkt", "스타렉스", 0,0,0,0,20000000,NULL);
SELECT LAST_INSERT_ID() as LAST;
SELECT * FROM Notification WHERE caryear_from <= 2019 <= caryear_to;
SELECT * FROM Notification WHERE model = "쏘나타" and caryear_from <= 2017 <= caryear_to and distance_from <= 34413 <= distance_to and price_from <= 19900000 <= price_to;
#drop table testToken;
#drop table usedCar;
#drop table carModel;
#drop table Notification;

SELECT * FROM Notification WHERE model = "스타렉스" and caryear_from <= 0 and 0 <= caryear_to and distance_from <= 0 
	and 0 <= distance_to and (price_from is NULL or price_from <= 20000000) and (price_to is NULL or 19900000 <= price_to);
DELETE FROM usedCar WHERE site = 'KB';